<?php

return [
    'groups' => [
        'Tenants' => [
            'Widget Click Tenant',
            'View Tenant List',
            'View Tenant Detail',
        ],
        'Promotions' => [
            'Widget Click Promotion',
            'View Promotion Pop Up',
            'Click Promotion Pop Up',
            'View Promotion List',
            'View Promotion Tenant List',
            'View Promotion Detail',
        ],
        'News' => [
            'Widget Click News',
            'View News Pop Up',
            'Click News Pop Up',
            'View News List',
            'View News Tenant List',
            'View News Detail',
        ],
        'Coupons' => [
            'Widget Click Coupon',
            'View Coupon Pop Up',
            'Click Coupon Pop Up',
            'View Coupon List',
            'View Coupon Tenant List',
            'View Coupon Detail',
            'View Coupon Campaign Detail',
            'View Coupon Redemption Places',
            'Coupon Issuance',
            'Read Coupon Issuance Notification',
            'Coupon Redemption (Successful)',
        ],
        'Lucky Draws' => [
            'Widget Click Lucky Draw',
            'View Lucky Draw List',
            'View Lucky Draw Detail',
            'Lucky Draw Number Issuance',
            'Read Lucky Draw Number Issuance Notification',
            'View Winning Numbers & Prizes',
            'Read Winner Announcement Notification',
        ],
        'Notifications' => [
            'Read Activation Notification',
            'Customer Activation',
            'Read Coupon Issuance Notification',
            'Read Lucky Draw Number Issuance Notification',
            'Read Winner Announcement Notification',
        ],
        'Pop Ups' => [
            'View Promotion Pop Up',
            'Click Promotion Pop Up',
            'View News Pop Up',
            'Click News Pop Up',
            'View Coupon Pop Up',
            'Click Coupon Pop Up',
        ],
        'Widgets' => [
            'Widget Click Tenant',
            'Widget Click Promotion',
            'Widget Click News',
            'Widget Click Coupon',
            'Widget Click Lucky Draw',
        ],
    ],
];
