<?php namespace Orbit\Controller\API\v1\Pub;
/**
 * API to read sitemap.xml generated by artisan
 * @author ahmad <ahmad@dominopos.com>
 */

use OrbitShop\API\v1\PubControllerAPI;
use Config;
use Illuminate\Support\Facades\Response;

class SitemapReaderAPIController extends PubControllerAPI
{
    public function getSitemap()
    {
        try {
            $filePath = storage_path();
            $fileName = Config::get('orbit.sitemap.filename', 'sitemap.xml');

            // return inline sitemap xml
            return Response::download($filePath . '/' . $fileName, $fileName, [], 'inline');
        } catch (\Exception $e) {
            return;
        }
    }

    public function getSitemapArticle()
    {
        try {
            $filePath = storage_path();
            $fileName = Config::get('orbit.sitemap.filename_article', 'sitemap-article.xml');

            // return inline sitemap xml
            return Response::download($filePath . '/' . $fileName, $fileName, [], 'inline');
        } catch (\Exception $e) {
            return;
        }
    }
}
